// INTERNAL ERROR //

/* Location:           F:\一周备份\面试apk\希望代码没混淆\jingmgou\jingmgou2\classes-dex2jar.jar
 * Qualified Name:     com.ismartgo.app.url.Url
 * JD-Core Version:    0.6.2
 */

package com.ismartgo.app.url;

public class Url
{
    public static String ABOUT_URL;
    public static String ADD_VIPCARD;
    public static String ADS_URL;
    public static String ADVERTISE_CLICK_URL;
    public static String ADVERTISE_URL;
    public static String ALL_RECEIPT_ACTIVITY_URL;
    public static String APPEAL_Url = "http://wx2.ismartgo.com/adminusrappeal/jsp/userAppeal.jsp?from=groupmessage&isappinstalled=0";
    public static String BEANNUMBER_BY_KEYWORD_URL;
    public static String BEANS_SCOPE_URL;
    public static String BIND_MOBILE;
    public static String BIND_WEICHAT;
    public static String CARD_INFO_LIST;
    public static String COLLECT_GOODS_URL;
    public static String DELETECOLLECTGOODS_URL;
    public static String DELETEMESSAGE_URL;
    public static String DELETE_USER_INFORMATION;
    public static String DEL_COLLECT_URL;
    public static String DEL_VIPCARD;
    public static String DETAIL_VIPCARD;
    public static String EARNSIGNBEANS_URL;
    public static String EXCHANGE_GIFT_URL;
    public static String FEEDBACK_URL;
    public static String FOCUS_RETAILS;
    public static String GET_AGREEMENT_URL;
    public static String GET_APP_SESSION;
    public static String GET_AREA;
    public static String GET_BEAN_BY_OPENAPP;
    public static String GET_CITY;
    public static String GET_EMAIL_VALID_CODE_URL;
    public static String GET_OOS_TOKEN;
    public static String GET_PROVINCE;
    public static String GET_SEARCH_TYPE;
    public static String GET_TOWN;
    public static String GET_USER_BEAN;
    public static String GET_USER_BEAN_DETAIL;
    public static String GET_USER_CONTACT;
    public static String GET_USER_INFO;
    public static String GET_USER_INVITE_HISTORY;
    public static String GET_VALID_CODE_URL;
    public static String GIFT_CATEGORY_URL;
    public static String GIFT_DETAIL_URL;
    public static String GIFT_SEARCH_URL;
    public static String GOODS_CLICK_URL;
    public static String GOODS_SCAN_LIST_URL;
    public static String HAS_JOIN_ACTIVITY_URL;
    public static String HOME_HEAD_MODE;
    public static String HOME_HEAD_TOP;
    public static String INQUIRY_IBEACON_DATA_URL;
    public static String INSTORE_DETAIL_URL;
    public static String INVITE_FRIEND_PAGE;
    public static String IN_SHOP_GOODS_SCAN_LIST_URL;
    public static String ISINSHOP_ISSCAN_URL;
    public static String LBS_IFNO_URL;
    public static String LOGIN_URL;
    public static String LOOK_OVER_LOGISTICS;
    public static String MEMBERSHIP_CARD_LIST;
    public static String MESSAGE_URL;
    public static String MODIFY_DATA_URL;
    public static String MODIFY_PHONE_URL;
    public static String MY_COLLECT_LIST_URL;
    public static String MY_FOCUS;
    public static String MY_GIFT_LIST_URL;
    public static String MY_GIFT_URL;
    public static String MY_RECEIPT_ADD;
    public static String MY_RECEIPT_DELETE;
    public static String MY_RECEIPT_LIST;
    public static String MY_RECEIPT_LOTTERY;
    public static String MY_RECEIPT_MODIFY;
    public static String MY_RECEIPT_SHOP_TYPE;
    public static String MY_RECEIPT_STATISTIC;
    public static String NEARBYMACKET_URL;
    public static String NEARBY_MORE_STORE;
    public static String NEW_NEARBYMACKET_URL;
    public static String NEW_PROMOTIONDETAIL_URL;
    public static String NEW_PROMOTIONOUTGOODS_URL;
    public static String OUTSHOPSIGN_URL;
    public static String PROMOTIONOUTGOODS_URL;
    public static String PROMOTIONSCREENAREA_URL;
    public static String RECEIPT_ACTIVITY_DETAIL_URL;
    public static String REGISTER_URL;
    public static String RESET_PASSWORD_URL;
    public static String RETAILERS_URL;
    public static String RETAILER_GET_SHOPID;
    public static String SCANGETBEANS_URL;
    public static String SCANMORE_URL;
    public static String SCREENSTORE_URL;
    public static String SEARCH_NEAR_RETAILS;
    public static String SEARCH_SHOP_URL;
    public static String SELECT_GOODS_URL;
    public static String SEND_VAILD_EMAIL;
    public static String SERVER_URL = "http://sv.ismartgo.cn:29090/appsv2";
    public static String SERVER_URL2 = "";
    public static String SET_USER_CONTACT;
    public static String SHARE_GOODS_URL;
    public static String SHOPPING_CARD_DETAILS;
    public static String SHOPPING_CARD_LIST;
    public static String SHOP_BRAND_URL;
    public static String SHOP_CATEGORY_URL;
    public static String SIGN_IN;
    public static String SMARTGO_LOGO_URL;
    public static String STORE_HOME_URL;
    public static String SYNCHRO_BEAN_NUMBER_URL;
    public static String THIRD_LOGIN_URL;
    public static String TOURIST_REGIST_URL;
    public static String UPDATEMESSAGE_URL;
    public static String UPLOAD_RECEIPT_URL;

    static
    {
        ADS_URL = "http://img.ismartgo.cn/";
        SMARTGO_LOGO_URL = "http://img.ismartgo.cn/data/logo/ismartgo.png";
        TOURIST_REGIST_URL = SERVER_URL + "/app/touristRegist.do";
        ADVERTISE_URL = SERVER_URL + "/app/getAdsPhoto.do";
        ADVERTISE_CLICK_URL = SERVER_URL + "/app/clickAdvert.do";
        GOODS_CLICK_URL = SERVER_URL + "/app/clickGoodsMsg.do";
        NEARBYMACKET_URL = SERVER_URL + "/app/getHomePageGoods.do";
        MESSAGE_URL = SERVER_URL + "/app/userMessage.do";
        UPDATEMESSAGE_URL = SERVER_URL + "/app/updateMessage.do";
        DELETEMESSAGE_URL = SERVER_URL + "/app/delMessage.do";
        SEARCH_SHOP_URL = SERVER_URL + "/app/searchShop.do";
        SELECT_GOODS_URL = SERVER_URL + "/app/selectGoods.do";
        SCREENSTORE_URL = SERVER_URL + "/app/getShopTypeList.do";
        RETAILERS_URL = SERVER_URL + "/app/getRetailList.do";
        PROMOTIONSCREENAREA_URL = SERVER_URL + "/app/getAreaData.do";
        SHOP_CATEGORY_URL = SERVER_URL + "/app/getShopTypesAndCategorys.do";
        SHOP_BRAND_URL = SERVER_URL + "/app/getShopBrand.do";
        PROMOTIONOUTGOODS_URL = SERVER_URL + "/app/outShopGoodsList.do";
        NEW_PROMOTIONOUTGOODS_URL = "/retails/getRetailPromotions.do";
        INSTORE_DETAIL_URL = SERVER_URL + "/app/checkMoreGoodsList.do";
        OUTSHOPSIGN_URL = SERVER_URL + "/app/shopSignList.do";
        SCANMORE_URL = SERVER_URL + "/app/checkMoreGoodsList.do";
        EARNSIGNBEANS_URL = SERVER_URL + "/app/earnSignBean.do";
        SCANGETBEANS_URL = SERVER_URL + "/app/earnBeanByScanGoods.do";
        ISINSHOP_ISSCAN_URL = SERVER_URL + "/app/isInShopAndIsScan.do";
        DELETECOLLECTGOODS_URL = SERVER_URL + "/app/deleteCollect.do";
        GET_AGREEMENT_URL = SERVER_URL + "/getAgreement.do";
        GET_VALID_CODE_URL = SERVER_URL + "/app/getValidCode.do";
        GET_EMAIL_VALID_CODE_URL = SERVER_URL + "/app/getEmailValidCode.do";
        SEND_VAILD_EMAIL = SERVER_URL + "/app/sendVaildEmail.do";
        REGISTER_URL = SERVER_URL + "/app/register.do";
        LOGIN_URL = SERVER_URL + "/app/login.do";
        THIRD_LOGIN_URL = SERVER_URL + "/app/thirdlogin.do";
        RESET_PASSWORD_URL = SERVER_URL + "/app/resetPassword.do";
        MODIFY_PHONE_URL = SERVER_URL + "/app/updatePhone.do";
        MODIFY_DATA_URL = SERVER_URL + "/app/updateUser.do";
        ABOUT_URL = SERVER_URL + "/app/userAgreeAbout.do";
        FEEDBACK_URL = SERVER_URL + "/app/feedBack.do";
        MY_GIFT_URL = SERVER_URL + "/app/mytowgift.do";
        BEANS_SCOPE_URL = SERVER_URL + "/app/beanScope.do";
        GIFT_CATEGORY_URL = SERVER_URL + "/app/giftCategory.do";
        GIFT_SEARCH_URL = SERVER_URL + "/app/searchGift.do";
        GIFT_DETAIL_URL = SERVER_URL + "/app/getGiftDetails.do";
        EXCHANGE_GIFT_URL = SERVER_URL + "/app/exchangeGift_new.do";
        MY_GIFT_LIST_URL = SERVER_URL + "/app/mygiftlist.do";
        COLLECT_GOODS_URL = SERVER_URL + "/app/collectGoods.do";
        DEL_COLLECT_URL = SERVER_URL + "/app/deleteCollect.do";
        MY_COLLECT_LIST_URL = SERVER_URL + "/app/myCollectList.do";
        GOODS_SCAN_LIST_URL = SERVER_URL + "/app/goodsScanList.do";
        IN_SHOP_GOODS_SCAN_LIST_URL = SERVER_URL + "/app/inShopGoodsScanList.do";
        INQUIRY_IBEACON_DATA_URL = SERVER_URL + "/app/getOneIbeacon.do";
        GET_BEAN_BY_OPENAPP = SERVER_URL + "/app/getBeanByOpenApp.do";
        BEANNUMBER_BY_KEYWORD_URL = SERVER_URL + "/app/getBeannumberByKeyWord.do";
        SYNCHRO_BEAN_NUMBER_URL = SERVER_URL + "/app/synchroBeanNumber.do";
        DELETE_USER_INFORMATION = SERVER_URL + "/app/delUserGift.do";
        GET_SEARCH_TYPE = SERVER_URL + "/app/getSearchType.do";
        SHARE_GOODS_URL = SERVER_URL + "/dm/shopshare.jsp?";
        LBS_IFNO_URL = SERVER_URL + "/app/lbsInfo.do";
        SIGN_IN = SERVER_URL + "/app/signInShop.do";
        GET_USER_BEAN = SERVER_URL + "/app/getUserBeans.do";
        GET_USER_INFO = SERVER_URL + "/app/getUserInfo.do";
        GET_USER_INVITE_HISTORY = SERVER_URL + "/app/getinvitehistory2.do";
        SET_USER_CONTACT = SERVER_URL + "/app/setUserContact.do";
        GET_USER_CONTACT = SERVER_URL + "/app/getUserContact.do";
        GET_USER_BEAN_DETAIL = SERVER_URL + "/app/myBean.do";
        ALL_RECEIPT_ACTIVITY_URL = SERVER_URL + "/app/allreceiptgames.do";
        RECEIPT_ACTIVITY_DETAIL_URL = SERVER_URL + "/app/receiptgamedetail.do";
        HAS_JOIN_ACTIVITY_URL = SERVER_URL + "/app/myreceipts.do";
        GET_OOS_TOKEN = SERVER_URL + "/app/getPhotoOssAuthorize.do";
        UPLOAD_RECEIPT_URL = SERVER_URL + "/app/joinreceiptgame.do";
        GET_APP_SESSION = SERVER_URL + "/app/getAppSessionId.do";
        LOOK_OVER_LOGISTICS = SERVER_URL + "/app/getLogisticsTrack.do";
        GET_PROVINCE = SERVER_URL + "/app/getProvince.do";
        GET_CITY = SERVER_URL + "/app/getCity.do";
        GET_AREA = SERVER_URL + "/app/getCounty.do";
        GET_TOWN = SERVER_URL + "/app/getTown.do";
        HOME_HEAD_MODE = SERVER_URL + "/app/gethomebuttonlist.do";
        HOME_HEAD_TOP = SERVER_URL + "/app/getsmartgoheadlines.do";
        MY_RECEIPT_LIST = SERVER_URL2 + "/getreceiptlist.do";
        MY_RECEIPT_STATISTIC = SERVER_URL2 + "/statbymonth.do";
        MY_RECEIPT_SHOP_TYPE = SERVER_URL2 + "/getshoptypelist.do";
        MY_RECEIPT_MODIFY = SERVER_URL2 + "/updatereceiptinfo.do";
        MY_RECEIPT_DELETE = SERVER_URL2 + "/deletereceiptinfo.do";
        MY_RECEIPT_ADD = SERVER_URL2 + "/addreceipt.do";
        MY_RECEIPT_LOTTERY = "http://120.25.206.97:29093/pubsv/receipt/lottery.jsp";
        NEW_NEARBYMACKET_URL = "/retails/getHomePagePromotions.do";
        NEARBY_MORE_STORE = "/retails/getShops.do";
        MY_FOCUS = "/retails/getSubscribeList.do";
        SEARCH_NEAR_RETAILS = "/retails/searchNearRetails.do";
        FOCUS_RETAILS = "/retails/subscribe.do";
        NEW_PROMOTIONDETAIL_URL = "/promotion/getPromotionDetail.do";
        STORE_HOME_URL = "/retails/getShopHomePage.do";
        MEMBERSHIP_CARD_LIST = "/usercard/getvipcardlist.do";
        CARD_INFO_LIST = "/usercard/getretailsforvipcard.do";
        ADD_VIPCARD = "/usercard/addvipcard.do";
        DETAIL_VIPCARD = "/usercard/getvipcarddetail.do";
        SHOPPING_CARD_LIST = "/usercard/getshoppingcardlist.do";
        SHOPPING_CARD_DETAILS = "/usercard/getshoppingcarddetail.do";
        DEL_VIPCARD = "/usercard/deletevipcard.do";
        RETAILER_GET_SHOPID = "/retails/getNearByShopId.do";
        BIND_MOBILE = SERVER_URL + "/app/bindmobile.do";
        BIND_WEICHAT = SERVER_URL + "/app/bindweixin.do";
        INVITE_FRIEND_PAGE = SERVER_URL + "/invite/invitedfriend.jsp";
    }
}
